import type { SkillCardData } from "@/components/SkillCard";

export const ALL_SKILLS: SkillCardData[] = [
  // 教培培训
  {
    id: "1",
    title: "学生课堂情绪分析",
    description: "上传录音/文字 → 生成情绪报告 + 家长沟通话术",
    industry: "教培培训",
    type: "skill_pack",
    installCount: 328,
    rating: 4.8,
    price: 0,
    coverImage: "🎯",
    tags: ["教培培训", "技能包"],
  },
  {
    id: "2",
    title: "学员流失预警",
    description: "追踪出勤/作业数据 → 关键节点自动提醒",
    industry: "教培培训",
    type: "workflow",
    installCount: 215,
    rating: 4.6,
    price: 0,
    coverImage: "🔔",
    tags: ["教培培训", "工作流"],
  },
  {
    id: "3",
    title: "个性化作业生成",
    description: "根据学员弱点 → 生成差异化练习题",
    industry: "教培培训",
    type: "skill_pack",
    installCount: 186,
    rating: 4.7,
    price: 0,
    coverImage: "📝",
    tags: ["教培培训", "技能包"],
  },
  {
    id: "4",
    title: "家长沟通话术生成",
    description: "输入课堂表现 → 输出个性化沟通文案",
    industry: "教培培训",
    type: "skill_pack",
    installCount: 274,
    rating: 4.9,
    price: 0,
    coverImage: "💌",
    tags: ["教培培训", "技能包"],
  },
  {
    id: "5",
    title: "课程销售跟进",
    description: "潜客记录 → 自动跟进提醒 + 成交话术",
    industry: "教培培训",
    type: "workflow",
    installCount: 163,
    rating: 4.5,
    price: 0,
    coverImage: "📈",
    tags: ["教培培训", "工作流"],
  },
  // 电商运营
  {
    id: "e1",
    title: "商品文案批量生成",
    description: "输入商品参数 → 一键生成多平台种草文案",
    industry: "电商运营",
    type: "skill_pack",
    installCount: 402,
    rating: 4.5,
    price: 0,
    coverImage: "✍️",
    tags: ["电商运营", "技能包"],
  },
  {
    id: "e2",
    title: "客服自动回复",
    description: "常见问题自动应答 → 减少80%重复咨询",
    industry: "电商运营",
    type: "workflow",
    installCount: 356,
    rating: 4.4,
    price: 0,
    coverImage: "💬",
    tags: ["电商运营", "工作流"],
  },
  {
    id: "e3",
    title: "竞品价格监控",
    description: "追踪竞品定价变动 → 自动生成调价建议",
    industry: "电商运营",
    type: "skill_pack",
    installCount: 178,
    rating: 4.3,
    price: 0,
    coverImage: "📊",
    tags: ["电商运营", "技能包"],
  },
  // 自媒体内容
  {
    id: "m1",
    title: "爆款选题生成器",
    description: "输入领域关键词 → 输出10个高潜力选题",
    industry: "自媒体内容",
    type: "skill_pack",
    installCount: 521,
    rating: 4.7,
    price: 0,
    coverImage: "🔥",
    tags: ["自媒体内容", "技能包"],
  },
  {
    id: "m2",
    title: "短视频脚本撰写",
    description: "给出主题 → 生成完整脚本+分镜建议",
    industry: "自媒体内容",
    type: "workflow",
    installCount: 445,
    rating: 4.6,
    price: 0,
    coverImage: "🎬",
    tags: ["自媒体内容", "工作流"],
  },
  {
    id: "m3",
    title: "多平台内容改写",
    description: "一篇内容 → 自动适配小红书/抖音/公众号风格",
    industry: "自媒体内容",
    type: "skill_pack",
    installCount: 389,
    rating: 4.5,
    price: 0,
    coverImage: "🔄",
    tags: ["自媒体内容", "技能包"],
  },
  // 销售客服
  {
    id: "s1",
    title: "客户跟进提醒",
    description: "自动追踪客户状态 → 最佳时机推送跟进建议",
    industry: "销售客服",
    type: "workflow",
    installCount: 267,
    rating: 4.5,
    price: 0,
    coverImage: "📞",
    tags: ["销售客服", "工作流"],
  },
  {
    id: "s2",
    title: "销售话术生成",
    description: "输入客户画像 → 生成个性化沟通话术",
    industry: "销售客服",
    type: "skill_pack",
    installCount: 312,
    rating: 4.4,
    price: 0,
    coverImage: "🗣️",
    tags: ["销售客服", "技能包"],
  },
  {
    id: "s3",
    title: "成交数据分析",
    description: "汇总销售数据 → 生成可视化报告 + 优化建议",
    industry: "销售客服",
    type: "skill_pack",
    installCount: 198,
    rating: 4.3,
    price: 0,
    coverImage: "📈",
    tags: ["销售客服", "技能包"],
  },
  // 设计创意
  {
    id: "d1",
    title: "设计需求拆解",
    description: "模糊需求 → 结构化设计任务清单",
    industry: "设计创意",
    type: "skill_pack",
    installCount: 156,
    rating: 4.6,
    price: 0,
    coverImage: "🎨",
    tags: ["设计创意", "技能包"],
  },
  {
    id: "d2",
    title: "配色方案生成",
    description: "输入品牌关键词 → 输出3套配色 + 使用指南",
    industry: "设计创意",
    type: "skill_pack",
    installCount: 201,
    rating: 4.5,
    price: 0,
    coverImage: "🌈",
    tags: ["设计创意", "技能包"],
  },
  {
    id: "d3",
    title: "UI文案优化",
    description: "输入界面截图描述 → 优化按钮/提示/引导文案",
    industry: "设计创意",
    type: "skill_pack",
    installCount: 134,
    rating: 4.4,
    price: 0,
    coverImage: "✨",
    tags: ["设计创意", "技能包"],
  },
  // 财务咨询
  {
    id: "f1",
    title: "财务报表解读",
    description: "上传报表 → 自动生成经营分析 + 风险提示",
    industry: "财务咨询",
    type: "skill_pack",
    installCount: 189,
    rating: 4.7,
    price: 0,
    coverImage: "📋",
    tags: ["财务咨询", "技能包"],
  },
  {
    id: "f2",
    title: "税务筹划建议",
    description: "输入企业情况 → 输出合规节税方案",
    industry: "财务咨询",
    type: "skill_pack",
    installCount: 145,
    rating: 4.5,
    price: 0,
    coverImage: "💰",
    tags: ["财务咨询", "技能包"],
  },
  {
    id: "f3",
    title: "发票智能分类",
    description: "批量上传发票 → 自动分类 + 生成报销单",
    industry: "财务咨询",
    type: "workflow",
    installCount: 223,
    rating: 4.6,
    price: 0,
    coverImage: "🧾",
    tags: ["财务咨询", "工作流"],
  },
];

export function getSkillById(id: string) {
  return ALL_SKILLS.find((s) => s.id === id);
}

export function getSkillsByIndustry(industry: string) {
  return ALL_SKILLS.filter((s) => s.industry === industry);
}

export function searchSkills(query: string) {
  const q = query.toLowerCase();
  return ALL_SKILLS.filter(
    (s) =>
      s.title.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.industry.toLowerCase().includes(q)
  );
}
