import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "path";

const dbUrl = process.env.DATABASE_URL || "file:./dev.db";
const dbFile = dbUrl.replace("file:", "").replace("./", "");
const dbPath = path.join(process.cwd(), dbFile);
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

async function main() {
  // Create admin user (Basion)
  const admin = await prisma.user.upsert({
    where: { phone: "13800000000" },
    update: {},
    create: {
      phone: "13800000000",
      nickname: "Basion",
      industry: "教培培训",
      avatar: "🧑‍🏫",
      bio: "ClawsBag 创始人，教培行业 Agent 先行者",
    },
  });

  console.log("✅ Admin user created:", admin.id);

  const skillPacksData = [
    {
      title: "学生课堂情绪分析",
      description: "上传录音/文字 → 生成情绪报告 + 家长沟通话术",
      industry: "教培培训",
      type: "skill_pack",
      price: 0,
      coverImage: "🎯",
      installCount: 328,
      rating: 4.8,
      ratingCount: 56,
      problem:
        "每节课结束，你需要花大量时间观察和记录学生的情绪状态，然后再费力组织语言给家长反馈。装上这个技能包后，你只需上传一节课的录音或文字记录，15分钟内就能得到：每个学生的情绪参与度报告、需要重点关注的学生标注、给对应家长的个性化沟通话术。",
      contents: JSON.stringify([
        { name: "课堂情绪识别", description: "从音频/文字中提取学生情绪特征" },
        { name: "情绪报告生成", description: "自动生成可视化的课堂情绪分析报告" },
        { name: "家长话术生成", description: "基于分析结果，生成个性化的家长沟通文案" },
        { name: "重点学生标注", description: "自动标记需要特别关注的学生" },
      ]),
      instructions: "安装后，在 Agent 中选择「课堂情绪分析」技能\n上传课堂录音文件或粘贴课堂文字记录\n等待 15 分钟，查收完整的分析报告",
      targetUser: "K12 教培机构老师、班主任、教学主管",
      notForUser: "大学讲师（内容偏向 K12 场景）、纯线上录播课",
      tags: ["教培培训", "情绪分析", "家长沟通"],
    },
    {
      title: "学员流失预警",
      description: "追踪出勤/作业数据 → 关键节点自动提醒",
      industry: "教培培训",
      type: "workflow",
      price: 0,
      coverImage: "🔔",
      installCount: 215,
      rating: 4.6,
      ratingCount: 34,
      problem: "学员流失往往有迹可循：连续缺课、作业不交、互动减少。但你很难同时关注几十甚至上百个学员的状态。这个工作流会自动追踪每个学员的关键行为数据，在流失风险升高时第一时间提醒你，并给出挽留建议。",
      contents: JSON.stringify([
        { name: "行为数据追踪", description: "自动记录出勤、作业、互动等关键指标" },
        { name: "流失风险评估", description: "基于多维数据计算流失概率" },
        { name: "预警通知", description: "风险达到阈值时自动推送提醒" },
        { name: "挽留建议", description: "针对不同情况生成个性化挽留方案" },
      ]),
      instructions: "安装后，录入学员名单和基础信息\n定期更新出勤和作业数据（支持批量导入）\n收到预警通知后，查看详情和建议执行挽留动作",
      targetUser: "教培机构教务、班主任、校区负责人",
      notForUser: "1对1私教（学员数量少，不需要系统化管理）",
      tags: ["教培培训", "学员管理", "预警"],
    },
    {
      title: "个性化作业生成",
      description: "根据学员弱点 → 生成差异化练习题",
      industry: "教培培训",
      type: "skill_pack",
      price: 0,
      coverImage: "📝",
      installCount: 186,
      rating: 4.7,
      ratingCount: 28,
      problem: "每个学生的薄弱点不同，统一布置作业效果差。这个技能包会分析学生的历史表现，自动生成针对性练习题。",
      contents: JSON.stringify([
        { name: "弱点分析", description: "从测试和作业记录中识别薄弱知识点" },
        { name: "题目生成", description: "基于弱点自动生成差异化练习题" },
      ]),
      instructions: "导入学生的历史测试成绩\n选择学科和知识范围\n自动生成个性化练习题",
      targetUser: "K12 老师、教培机构",
      notForUser: "成人教育、职业培训",
      tags: ["教培培训", "作业", "个性化"],
    },
    {
      title: "家长沟通话术生成",
      description: "输入课堂表现 → 输出个性化沟通文案",
      industry: "教培培训",
      type: "skill_pack",
      price: 0,
      coverImage: "💌",
      installCount: 274,
      rating: 4.9,
      ratingCount: 42,
      problem: "跟家长沟通是一门艺术，说重了家长不高兴，说轻了没效果。这个技能包帮你根据学生的具体表现，生成得体又有针对性的沟通话术。",
      contents: JSON.stringify([
        { name: "表现分析", description: "从课堂数据中提取关键表现点" },
        { name: "话术生成", description: "生成正面+建设性的沟通文案" },
      ]),
      instructions: "输入学生当日课堂表现要点\n选择沟通场景（日常/问题/表扬）\n获取个性化话术",
      targetUser: "K12 老师、班主任",
      notForUser: "无需家长沟通的场景",
      tags: ["教培培训", "家长沟通", "话术"],
    },
    {
      title: "课程销售跟进",
      description: "潜客记录 → 自动跟进提醒 + 成交话术",
      industry: "教培培训",
      type: "workflow",
      price: 0,
      coverImage: "📈",
      installCount: 163,
      rating: 4.5,
      ratingCount: 22,
      problem: "潜在客户多了就容易忘记跟进，错过最佳成交时机。这个工作流自动记录潜客状态，在最佳时机提醒你跟进，并提供成交话术。",
      contents: JSON.stringify([
        { name: "潜客管理", description: "记录和追踪潜在客户信息" },
        { name: "跟进提醒", description: "基于客户行为自动推送跟进提醒" },
        { name: "成交话术", description: "根据客户画像生成个性化话术" },
      ]),
      instructions: "录入潜在客户信息\n系统自动追踪并推送跟进提醒\n查看针对性话术并执行跟进",
      targetUser: "教培机构课程顾问、销售",
      notForUser: "不涉及课程销售的岗位",
      tags: ["教培培训", "销售", "跟进"],
    },
    {
      title: "商品文案批量生成",
      description: "输入商品参数 → 一键生成多平台种草文案",
      industry: "电商运营",
      type: "skill_pack",
      price: 0,
      coverImage: "✍️",
      installCount: 402,
      rating: 4.5,
      ratingCount: 48,
      problem: "每次上新品或活动，几十个SKU的文案要同时更新，还要适配不同平台风格。这个技能包输入商品参数就能批量生成淘宝/京东/小红书/抖音的文案。",
      contents: JSON.stringify([
        { name: "商品参数提取", description: "结构化提取商品卖点和参数" },
        { name: "多平台文案生成", description: "一键生成适配多个平台的文案" },
        { name: "风格适配", description: "自动适配小红书/淘宝/抖音等平台风格" },
      ]),
      instructions: "输入商品参数（材质、卖点、目标人群）\n选择目标平台\n获取多平台文案",
      targetUser: "电商运营、店铺客服、品牌方",
      notForUser: "不涉及商品文案的岗位",
      tags: ["电商运营", "文案", "多平台"],
    },
    {
      title: "客服自动回复",
      description: "常见问题自动应答 → 减少80%重复咨询",
      industry: "电商运营",
      type: "workflow",
      price: 0,
      coverImage: "💬",
      installCount: 356,
      rating: 4.4,
      ratingCount: 38,
      problem: "客服每天面对大量重复问题。这个工作流自动识别常见问题并生成标准回复，减少80%的重复劳动。",
      contents: JSON.stringify([
        { name: "问题识别", description: "自动识别客户问题类型" },
        { name: "答案匹配", description: "从知识库匹配最佳回复" },
        { name: "话术优化", description: "根据语境优化回复语气" },
      ]),
      instructions: "导入常见问题和标准答案\n开启自动回复功能\n人工审核和调整特殊情况",
      targetUser: "电商客服、客服主管",
      notForUser: "需要高度个性化沟通的高端客户服务",
      tags: ["电商运营", "客服", "自动化"],
    },
    {
      title: "竞品价格监控",
      description: "追踪竞品定价变动 → 自动生成调价建议",
      industry: "电商运营",
      type: "skill_pack",
      price: 0,
      coverImage: "📊",
      installCount: 178,
      rating: 4.3,
      ratingCount: 20,
      problem: "竞品价格波动直接影响你的销量。这个技能包自动追踪竞品价格变化，生成调价建议。",
      contents: JSON.stringify([
        { name: "价格追踪", description: "自动监控竞品价格变动" },
        { name: "调价建议", description: "基于市场数据生成定价策略" },
      ]),
      instructions: "输入竞品链接或关键词\n设置监控频率\n收到价格变动和调价建议通知",
      targetUser: "电商运营、品类经理",
      notForUser: "品牌调性优先于价格竞争的高端品牌",
      tags: ["电商运营", "价格", "监控"],
    },
    {
      title: "爆款选题生成器",
      description: "输入领域关键词 → 输出10个高潜力选题",
      industry: "自媒体内容",
      type: "skill_pack",
      price: 0,
      coverImage: "🔥",
      installCount: 521,
      rating: 4.7,
      ratingCount: 62,
      problem: "做自媒体最头疼的就是选题。这个技能包基于当前热门趋势，给你推荐高潜力选题和建议切入角度。",
      contents: JSON.stringify([
        { name: "热门趋势抓取", description: "实时分析各平台热门话题" },
        { name: "选题生成与评分", description: "生成选题并评估热度潜力" },
      ]),
      instructions: "输入你的领域关键词\n获取10个高潜力选题及热度评分\n选择感兴趣的选题开始创作",
      targetUser: "自媒体博主、内容创作者",
      notForUser: "不依赖平台流量的企业号",
      tags: ["自媒体内容", "选题", "爆款"],
    },
    {
      title: "短视频脚本撰写",
      description: "给出主题 → 生成完整脚本+分镜建议",
      industry: "自媒体内容",
      type: "workflow",
      price: 0,
      coverImage: "🎬",
      installCount: 445,
      rating: 4.6,
      ratingCount: 50,
      problem: "有了选题但写脚本费时间。这个工作流根据你的主题生成完整脚本和分镜建议。",
      contents: JSON.stringify([
        { name: "脚本生成", description: "根据主题生成完整视频脚本" },
        { name: "分镜建议", description: "自动生成画面分镜建议" },
      ]),
      instructions: "输入视频主题和目标时长\n获取完整脚本+分镜\n根据需要微调后开始拍摄",
      targetUser: "短视频创作者、MCN团队",
      notForUser: "纯文字创作者",
      tags: ["自媒体内容", "短视频", "脚本"],
    },
    {
      title: "多平台内容改写",
      description: "一篇内容 → 自动适配小红书/抖音/公众号风格",
      industry: "自媒体内容",
      type: "skill_pack",
      price: 0,
      coverImage: "🔄",
      installCount: 389,
      rating: 4.5,
      ratingCount: 44,
      problem: "同一个内容在不同平台需要不同风格。这个技能包一键把内容改写成适配各平台的版本。",
      contents: JSON.stringify([
        { name: "风格分析", description: "分析目标平台的内容风格特点" },
        { name: "内容改写", description: "保留核心信息，适配平台调性" },
      ]),
      instructions: "粘贴原始内容\n选择目标平台\n获取改写后的多个版本",
      targetUser: "多平台运营的创作者",
      notForUser: "单平台运营者",
      tags: ["自媒体内容", "多平台", "改写"],
    },
    {
      title: "客户跟进提醒",
      description: "自动追踪客户状态 → 最佳时机推送跟进建议",
      industry: "销售客服",
      type: "workflow",
      price: 0,
      coverImage: "📞",
      installCount: 267,
      rating: 4.5,
      ratingCount: 30,
      problem: "客户多了容易忘记跟进。这个工作流自动追踪客户状态，在最佳时机提醒你行动。",
      contents: JSON.stringify([
        { name: "客户状态追踪", description: "自动记录客户互动历史" },
        { name: "跟进时机计算", description: "基于行为数据推荐最佳跟进时间" },
      ]),
      instructions: "录入客户信息和互动记录\n系统自动推送跟进提醒\n查看建议并执行跟进",
      targetUser: "销售人员、客户经理",
      notForUser: "不涉及客户跟进的岗位",
      tags: ["销售客服", "跟进", "CRM"],
    },
    {
      title: "销售话术生成",
      description: "输入客户画像 → 生成个性化沟通话术",
      industry: "销售客服",
      type: "skill_pack",
      price: 0,
      coverImage: "🗣️",
      installCount: 312,
      rating: 4.4,
      ratingCount: 35,
      problem: "不同客户需要不同话术。这个技能包根据客户画像生成个性化的沟通策略和话术。",
      contents: JSON.stringify([
        { name: "客户画像分析", description: "理解客户类型和需求" },
        { name: "话术生成", description: "生成针对性的沟通话术" },
      ]),
      instructions: "输入客户背景信息\n选择沟通目的（首次接触/跟进/促单）\n获取个性化话术",
      targetUser: "销售人员、BD",
      notForUser: "标准化服务场景",
      tags: ["销售客服", "话术", "个性化"],
    },
    {
      title: "成交数据分析",
      description: "汇总销售数据 → 生成可视化报告 + 优化建议",
      industry: "销售客服",
      type: "skill_pack",
      price: 0,
      coverImage: "📈",
      installCount: 198,
      rating: 4.3,
      ratingCount: 18,
      problem: "销售数据散落各处，难以系统分析。这个技能包自动汇总数据生成报告和优化建议。",
      contents: JSON.stringify([
        { name: "数据汇总", description: "自动整合多源销售数据" },
        { name: "报告生成", description: "生成可视化分析报告" },
      ]),
      instructions: "导入或连接销售数据源\n选择分析维度和时间范围\n获取分析报告和建议",
      targetUser: "销售主管、运营负责人",
      notForUser: "一线销售人员",
      tags: ["销售客服", "数据", "分析"],
    },
    {
      title: "设计需求拆解",
      description: "模糊需求 → 结构化设计任务清单",
      industry: "设计创意",
      type: "skill_pack",
      price: 0,
      coverImage: "🎨",
      installCount: 156,
      rating: 4.6,
      ratingCount: 16,
      problem: "客户需求经常模糊不清。这个技能包帮你把模糊需求拆解成清晰的设计任务清单。",
      contents: JSON.stringify([
        { name: "需求理解", description: "解析模糊需求中的关键信息" },
        { name: "任务拆解", description: "生成结构化的设计任务清单" },
      ]),
      instructions: "粘贴客户的原始需求描述\n获取结构化的任务清单\n按清单逐项执行设计",
      targetUser: "设计师、设计团队负责人",
      notForUser: "已有完善需求管理流程的大型团队",
      tags: ["设计创意", "需求", "任务管理"],
    },
    {
      title: "配色方案生成",
      description: "输入品牌关键词 → 输出3套配色 + 使用指南",
      industry: "设计创意",
      type: "skill_pack",
      price: 0,
      coverImage: "🌈",
      installCount: 201,
      rating: 4.5,
      ratingCount: 22,
      problem: "配色是设计中最纠结的环节。这个技能包根据品牌调性自动生成专业配色方案。",
      contents: JSON.stringify([
        { name: "品牌分析", description: "理解品牌调性和目标感受" },
        { name: "配色生成", description: "生成3套配色方案+使用规范" },
      ]),
      instructions: "输入品牌名称和关键词\n获取3套配色方案\n选择方案并查看使用指南",
      targetUser: "平面设计师、UI设计师、品牌设计师",
      notForUser: "已有品牌色规范的项目",
      tags: ["设计创意", "配色", "品牌"],
    },
    {
      title: "UI文案优化",
      description: "输入界面截图描述 → 优化按钮/提示/引导文案",
      industry: "设计创意",
      type: "skill_pack",
      price: 0,
      coverImage: "✨",
      installCount: 134,
      rating: 4.4,
      ratingCount: 14,
      problem: "好的UI文案能大幅提升用户体验。这个技能包帮你优化界面上所有的按钮、提示和引导文案。",
      contents: JSON.stringify([
        { name: "文案审查", description: "识别可优化的UI文案" },
        { name: "文案优化", description: "生成更清晰、更有引导力的文案" },
      ]),
      instructions: "描述你的界面元素和当前文案\n获取优化建议\n按建议更新UI文案",
      targetUser: "产品经理、UI设计师、前端开发",
      notForUser: "非UI相关的文案场景",
      tags: ["设计创意", "UI", "文案"],
    },
    {
      title: "财务报表解读",
      description: "上传报表 → 自动生成经营分析 + 风险提示",
      industry: "财务咨询",
      type: "skill_pack",
      price: 0,
      coverImage: "📋",
      installCount: 189,
      rating: 4.7,
      ratingCount: 24,
      problem: "看财务报表头疼？这个技能包帮你自动解读报表，生成通俗易懂的经营分析报告和风险提示。",
      contents: JSON.stringify([
        { name: "报表解析", description: "自动识别和提取报表关键数据" },
        { name: "分析报告", description: "生成通俗易懂的经营分析" },
      ]),
      instructions: "上传财务报表文件\n选择分析维度\n获取经营分析报告",
      targetUser: "中小企业主、财务人员",
      notForUser: "需要审计级别精度的场景",
      tags: ["财务咨询", "报表", "分析"],
    },
    {
      title: "税务筹划建议",
      description: "输入企业情况 → 输出合规节税方案",
      industry: "财务咨询",
      type: "skill_pack",
      price: 0,
      coverImage: "💰",
      installCount: 145,
      rating: 4.5,
      ratingCount: 18,
      problem: "税务筹划门槛高但影响大。这个技能包根据你的企业情况给出合规的节税建议。",
      contents: JSON.stringify([
        { name: "企业分析", description: "理解企业类型和经营状况" },
        { name: "筹划建议", description: "生成合规的节税方案" },
      ]),
      instructions: "输入企业基本信息和经营数据\n获取税务筹划建议\n建议与专业税务师确认后执行",
      targetUser: "中小企业主、财务总监",
      notForUser: "需要法律级别税务意见的场景",
      tags: ["财务咨询", "税务", "筹划"],
    },
    {
      title: "发票智能分类",
      description: "批量上传发票 → 自动分类 + 生成报销单",
      industry: "财务咨询",
      type: "workflow",
      price: 0,
      coverImage: "🧾",
      installCount: 223,
      rating: 4.6,
      ratingCount: 26,
      problem: "每月处理大量发票是痛苦的重复劳动。这个工作流自动识别、分类发票并生成报销单。",
      contents: JSON.stringify([
        { name: "发票识别", description: "自动识别发票信息" },
        { name: "智能分类", description: "按类型和项目自动归类" },
        { name: "报销单生成", description: "自动汇总生成报销单" },
      ]),
      instructions: "批量上传发票照片或PDF\n系统自动识别和分类\n确认后生成报销单",
      targetUser: "财务人员、行政",
      notForUser: "已有完善发票管理系统的企业",
      tags: ["财务咨询", "发票", "自动化"],
    },
  ];

  for (const data of skillPacksData) {
    const { tags, ...skillData } = data;
    const pack = await prisma.skillPack.create({
      data: {
        ...skillData,
        authorId: admin.id,
        status: "approved",
        tags: {
          create: tags.map((t) => ({ tagName: t })),
        },
      },
    });
    console.log(`  📦 ${pack.title}`);
  }

  console.log(`\n✅ Seeded ${skillPacksData.length} skill packs`);

  // Create sample case
  const skillPack1 = await prisma.skillPack.findFirst({
    where: { title: "学生课堂情绪分析" },
  });

  if (skillPack1) {
    const sampleCase = await prisma.case.create({
      data: {
        title: "我的课后反馈时间从1小时缩短到15分钟",
        content: `我在杭州一家教培机构做了5年英语老师，带着3个班，每班20个学生。每节课结束后，我最头疼的事情就是写课后反馈。有一天同事跟我说她在用一个叫 ClawsBag 的工具，里面有个"课堂情绪分析"的技能包。我试了一下，把课堂录音传上去，15分钟就出来了结果。现在我每天至少省了2个多小时。`,
        industry: "教培培训",
        metricLabel: "节省时间",
        metricValue: "75%",
        city: "杭州",
        status: "approved",
        userId: admin.id,
        skillPacks: {
          create: { skillPackId: skillPack1.id },
        },
      },
    });
    console.log(`\n✅ Sample case created: ${sampleCase.title}`);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
